[theme]

# Primary accent for interactive elements
primaryColor = '#ff8200'

# Background color for the main content area
backgroundColor = '#333333'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#8d8d8d'

# Color used for almost all text
textColor = '#ffffff'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"